import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { auth, signOut } from "@/auth";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: { children: React.ReactNode }) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={inter.className}>
        <pre style={{ marginBottom: "1rem" }}>
          {JSON.stringify({ session }, null, 2)}
        </pre>
        <SessionProvider
          session={session}
          refetchInterval={30}
          refetchOnWindowFocus={true}
        >
          <ul>
            <li style={{ marginBottom: "1rem" }}>
              <Link href="/">Go home</Link>
            </li>
            <li style={{ marginBottom: "1rem" }}>
              <Link href="/login">Go to login</Link>
            </li>
            <li style={{ marginBottom: "1rem" }}>
              <Link href="/protected-rsc">Go to protected RSC</Link>
            </li>
            {session && (
              <li style={{ marginBottom: "1rem" }}>
                <form
                  action={async () => {
                    "use server";

                    await signOut({
                      redirectTo: "/login",
                    });
                  }}
                >
                  <button type="submit">Sign Out</button>
                </form>
              </li>
            )}
          </ul>

          <div style={{ marginTop: "1rem" }}>{children}</div>
        </SessionProvider>
      </body>
    </html>
  );
}
